### ISSUE TITLE
Disable convert text to date 

### ISSUE THREAD

**Issue by ekhtiari** [StrutTower/HtmlToExcel#1]
Hi . thanks for your package .
I Have a little problem with exported excel file .
In one of cell  I have this data : '5/16'
when I export date by this package In excel file I get this data : '5/16/2022'
witch setting must set to disable this convert . thanks

**Comment by StrutTower** [comment]
Thanks for submitting the issue. I just published version 2.1.0 that has two new data attributes, data-type and data-format. You should be able to use data-type="Text" on the table cell to force it to format the cell as text.
