### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by Gerardo-Sista** [StrutTower/HtmlToExcel#2]
Hello,
I installed nuget package into WPF application (but will use in ASP.NET core app) to test your software.

Unfortunateley, once started the app (no build fails) the following message appear:
"System.IO.FileNotFoundException: 'Could not load file or assembly 'HtmlToExcel, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. 

How to solve?  Consider I cannot install in GAC once in ASP.NET core environment

Visual Studio 2022 preview 6
WPF app targeting .net6

Thank you

**Comment by StrutTower** [comment]
I haven't tried it in a WPF app before. I don't have access to Visual Studio right now so I'll try to explain it off the top of head. 

Expand the references of your project in the Solution Explorer and find HtmlToExcel. Right click on it and select properties. Then make sure Copy Local is set to True.
